[package]
name = "ag"
version = "0.6.0"
authors = ["Russell Cohen <russell.r.cohen@gmail.com>"]
description = ["CLI App to slice and dice logfiles"]
license = "MIT"

[dependencies]
serde_json = "1.0"
itertools = "0.7.6"
ord_subset = "3.1.0"
nom = "4.0.0-beta1"
clap = "2.30.0"
regex = "0.2"
regex-syntax = "0.2"
terminal_size = "0.1.7"
quantiles = "0.7.1"

[dev-dependencies]
assert_cli = "0.5"
maplit = "1.0.1"